# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 简简
subtitle: 慢慢来，比较快！
description: 悄无声息地变坚强，安静地变优秀！
keywords: "简简,简简博客,简简的博客,信息安全,CTF,渗透测试,Web,网络安全"
author: 简简
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://jwt1399.top
root: /
#permalink: :title.html #:year/:month/:day/:title/
permalink_defaults:
#permalink_pinyin:
#  enable: true
#  separator: '-' # default: '-'
#permalink: :title/ 
permalink: posts/:abbrlink.html 
abbrlink: 
  alg: crc16 # 算法：crc16(default) and crc32 
  rep: dec # 进制：dec(default) and hex


# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 
  - "navigation/cn/*"
  - "navigation/assets/**"

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true

highlight:
  enable: false

prism_plugin:
  mode: 'preprocess'    
  theme: 'tomorrow'
  line_number: true    
  custom_css:

baidusitemap:
path: baidusitemap.xml

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 12
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 12
pagination_dir: page

search:
  path: search.xml
  field: post
  

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: matery-2.0

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repo: 
    github: https://github.com/jwt1399/jwt1399.github.io.git
    coding: git@e.coding.net:jwt1399/jwt.git
  branch: master
  deploy:
- type: baidu_url_submitter
  deploy:
- type: upyun 
  bucket: image-jwt1399
  operator: jwt
  password: iywfqB1Vm0UknEC81BSCDEatEuZkldy2
  endpoint: v0.api.upyun.com
  secret: secret
  try_times: 5
  ignore_path_re:
    dir: null
    file: ".DS_Store$"   
  
baidu_url_submit:
  count: 80             # 提交最新的一个链接
  host: jwt1399.top # 在百度站长平台中注册的域名
  token: i9he1f0OV7QenYuX # 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt  # 文本文档的地址， 新链接会保存在此文本文档里  
  
feed:
  type: atom #RSS的类型(atom/rss2)
  path: atom.xml #文件路径,默认是atom.xml/rss2.xml
  limit: false #展示文章的数量,使用0或则false代表展示全部
  hub:
  content: true  #在RSS文件中是否包含内容 ,有3个值 true/false默认不填为false
  content_limit: 140 #指定内容的长度作为摘要,仅仅在上面content设置为false和没有自定义的描述出现
  content_limit_delim: ' ' 
  order_by: -date  
  
backup:
  type: git
  theme: matery-2.0
  message: Back up my blog
  repository:
    github: https://github.com/jwt1399/jwt1399.github.io.git,blog_source
    coding: git@e.coding.net:jwt1399/jwt.git,blog_source
    

 
    

  
  